name: TSProjectGenerator
kind: pipeline
type: docker

steps:
  - name: install
    image: node
    commands:
      - npm install --unsafe-perm
  - name: build
    image: node
    depends_on:
      - install
    commands:
      - npm run build
  - name: lint
    image: node
    depends_on:
      - install
    commands:
      - npm run lint
  - name: test
    image: node:lts
    depends_on:
      - build
    commands:
      - npm run test
  - name: publish package to npm
    image: node
    depends_on:
      - lint
      - test
    environment:
      NPM_TOKEN:
        from_secret: npm_token
    commands:
      - echo "//registry.npmjs.org/:_authToken=$${NPM_TOKEN}" > ~/.npmrc
      - npx lerna publish from-package -y
    when:
      event:
        - tag
      ref:
        - refs/tags/v[0-9]*.[0-9]*.[0-9]*
  - name: publish package to github
    image: node
    depends_on:
      - lint
      - test
    environment:
      GITHUB_TOKEN:
        from_secret: github_packages_token
    commands:
      - echo "//npm.pkg.github.com/:_authToken=$${GITHUB_TOKEN}" > ~/.npmrc
      - echo "registry=https://npm.pkg.github.com" >> ~/.npmrc
      - npx lerna publish from-package -y
    when:
      event:
        - tag
      ref:
        - refs/tags/v[0-9]*.[0-9]*.[0-9]*
  - name: prepare release
    image: node
    depends_on:
      - lint
      - test
    commands:
      - npx lerna exec --no-private -- npm pack
      - npm install escape-string-regexp --no-save
      - node -e "console.log(require('escape-string-regexp')('${DRONE_TAG}'))" > TagName.txt
    when:
      event:
        - tag
  - name: prepare release notes
    image: alpine
    depends_on:
      - prepare release
    commands:
      - export TagName=$$(cat TagName.txt)
      - export TagHeading="/## \(.* \($${TagName}\|\[$${TagName}\]\)\)\$/"
      - export HeadingPattern='/## \(.* \(v[0-9.]*\|\[.*\]\)\)/'
      - cp -f CHANGELOG.md ReleaseNotes.md
      - sed -i "1,$${TagHeading}{ $${TagHeading}P ; d } ; $${HeadingPattern},\$d" ReleaseNotes.md
      - cp -f ReleaseNotes.md ReleaseTitle.md
      - sed -i "2,\$d ; s$${HeadingPattern}\\\\1/" ReleaseTitle.md
    when:
      event:
        - tag
  - name: publish release
    image: plugins/github-release
    depends_on:
      - prepare release notes
    commands: []
    settings:
      api_key:
        from_secret: github_publish_token
      files:
        - "./packages/*/*.tgz"
      title: ReleaseTitle.md
      note: ReleaseNotes.md
    when:
      event:
        - tag

trigger:
  ref:
    - refs/heads/**
    - refs/pull/**
    - refs/tags/**
  event:
    - push
    - pull_request
    - tag
